### ISSUE TITLE
Add prefix to url_variables

### ISSUE THREAD

**Issue by jrecasens** [h-janes/flask-sitemapper#15]
Hello,

I have a multilingual blueprint and I am using a prefix to access each language e.g. .../es/category to access the spanish site, .../en/category to access the english category site, etc.

However, When using the `url_variables` functionality (e.g. `url_variables={"lang_code": ['es']`}), as expected, I get the following:

```
<url>
<loc>.../category</loc>
</url>
<url>
<loc>.../category?lang_code=es</loc>
</url>
<url>
```

Is there a way to get the XML syntax to show a **... /es/category** format instead of **.../category?lang_code=es**? I need this format for Google indexing.

Thank you!

**Comment by h-janes** [comment]
Hi, sorry for the long wait. Please could you provide your code for the relevant route functions?

**Comment by h-janes** [comment]
To make sure I am understanding correctly, I have tried to set up a similar test application:
```python
import flask
from flask_sitemapper import Sitemapper

sitemapper = Sitemapper()

# blueprints

english_blueprint = flask.Blueprint("english", __name__, url_prefix="/en")
@sitemapper.include()
@english_blueprint.route("/category")
def english_category():
    return "Hello"


spanish_blueprint = flask.Blueprint("spanish", __name__, url_prefix="/es")
@sitemapper.include()
@spanish_blueprint.route("/category")
def spanish_category():
    return "Hola"

# app

app = flask.Flask(__name__)
app.register_blueprint(english_blueprint)
app.register_blueprint(spanish_blueprint)

sitemapper.init_app(app)

@app.route("/sitemap.xml")
def sitemap():
    return sitemapper.generate()

app.run("127.0.0.1", 8000)
```

This is working for me and giving the following sitemap:
```xml
<?xml version="1.0" encoding="utf-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://127.0.0.1:8000/en/category</loc>
  </url>
  <url>
    <loc>https://127.0.0.1:8000/es/category</loc>
  </url>
</urlset>
```

If you are using flask blueprint URL prefixes, you do not need to use the `url_variables` parameter in the `@include` decorator. I believe doing this could be causing your issue. The `url_variables` parameter is instead for structures like this:
```python
@sitemapper.include(url_variables={"lang_id": ["es", "en"]})
@app.route("/<lang_id>/category")
def category(lang_id):
    translations = {"en": "Hello", "es": "Hola"}
    return translations.get(lang_id)
```

Please let me know if this solves your issue or if I have misunderstood you. Thanks!

**Comment by h-janes** [comment]
Closing this issue as I cannot help further without seeing the original code. My previous response may be of help. Feel free to reopen this issue if needed.

**Comment by jrecasens** [comment]
I am using a multilingual Blueprint, so there is no need to manually create one for each language:

`multilingual = Blueprint('multilingual', __name__, url_prefix='/<lang_code>')`

I ended up solving the issue by passing the language as a list: 

```

@app.route("/sitemap.xml")
def sitemap():
    # 1) reset sitemapper so old entries don't build up
    sitemapper.urls = []
    sitemapper.dynamic_endpoints = []
    sitemapper.cached_xml = None

    # 2) define the endpoints you want
    endpoints_to_add = [
        "home", ...
        "about",
        "contact_us",
    ]

    # add the default language routes (assuming "en" is your default)
    for ep in endpoints_to_add:
        sitemapper.add_endpoint(ep, lastmod=Config.DATE_LAST_MOD)

    # Exclude the default language
    lang_to_add = [lang for lang in Config.LANGUAGES if lang != Config.LANGUAGE_DEFAULT]
    for lang in lang_to_add:
        for endpoint in endpoints_to_add:
            sitemapper.add_endpoint(
                f"multilingual.{endpoint}",
                lastmod=Config.DATE_LAST_MOD,
                url_variables={"lang_code": [lang]}  # pass as a list
            )

    return sitemapper.generate()
```
