### ISSUE TITLE
Combining sitemapper instances

### ISSUE THREAD

**Issue by h-janes** [h-janes/flask-sitemapper#17]
Do you have a way to combine two Sitemapper instances? I have a Sitemapper instance in my `auth.py` and another in my `views.py` which I want to merge as a single xml.

_Originally posted by @TheLostProgrammer in https://github.com/h-janes/flask-sitemapper/issues/12#issuecomment-2028000549_

**Comment by h-janes** [comment]
Thanks for the feedback

For merging sitemapper instances, I'm sure there is a hacky way, something like this might work:
```python
from somewhere import sitemapper1
from somewhere_else import sitemapper2

sitemapper1.urls += sitemapper2.urls
sitemapper1.dynamic_endpoints += sitemapper2.dynamic_endpoints # only for v1.8.0 +
```

However, I would not recommend this as it may cause issues and may not be supported in future releases. Instead, I would use a single sitemapper instance (defined in something like `extensions.py` and import it into both `auth.py` and `views.py`. Then, import it to wherever you are defining your `Flask` app instance, use `sitemapper.init_app(app)` (after registering any blueprints if applicable), and define your `/sitemap.xml` route there.

example:
`extensions.py`
```python
from flask_sitemapper import Sitemapper
sitemapper = Sitemapper()
...
```

`auth.py` and `views.py`
```python
from extensions import sitemapper
...
```

`app.py` (or wherever you define your `Flask` instance)
```python
from extensions import sitemapper

...

sitemapper.init_app(app)

@app.route("/sitemap.xml")
def sitemap():
    return sitemapper.generate()
```


Alternatively, you could use a sitemap index to collate two separate sitemaps. See https://github.com/h-janes/flask-sitemapper/wiki/Usage#sitemap-indexes

**Comment by TheLostProgrammer** [comment]
Hey, thanks for helping out.

I had this working before the most recent commit and it appears where I was combining the lists was causing the problem. After moving it outside the route like in the example you provided, it appears to work fine now. Thanks again.

**Comment by h-janes** [comment]
Out of curiosity, why are you using multiple sitemappers and merging them? Just wondering if you are having issues using a single instance or just prefer to do it this way.

**Comment by TheLostProgrammer** [comment]
I have my authentication for users done in a seperate file for maintenance purposes. It just keeps the authentication side of the web app away from the main application. I could merge the two together, but it has been designed like this for a fair while now and merging the two would take a little while. In the future, there are planned updates, so I will just add that to the plans.

**Comment by h-janes** [comment]
Ah ok thanks. If you are going to use this method, I think the best way is to do this inside the route function in order to allow the new `Callable` url_variables to work properly. However, to avoid adding more URLs to the sitemap on each request, I have used sets. As far as I can tell, this method does not cause any issues and retains all functionality, including the features of the latest release.

```python
from somewhere import sm1 # Sitemapper instance
from somewhere_else import sm2 # Sitemapper instance

...

@app.route("/sitemap.xml")
def r_sitemap():
    sm1.urls = list(set(sm1.urls + sm2.urls))
    sm1.dynamic_endpoints = list(set(sm1.dynamic_endpoints + sm2.dynamic_endpoints))
    return sm1.generate()
```

edit: actually I don't think it needs to be inside the route function for new features to work, the first method should work fine too. I think I've had enough Flask Sitemapper for one day.
