### ISSUE TITLE
Dynamic URLS do not work. 

### ISSUE THREAD

**Issue by deepdatadive** [h-janes/flask-sitemapper#5]
I tried getting the sitemapper working, but even with your code example for dynamic routes I still get an error:

werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'blog_bp.r_user'. Did you forget to specify values ['user_id']?

@sitemapper.include(url_variables={"user_id": [1, 2, 3]})
@blog_bp.route("/user/<int:user_id>")
def r_user(user_id):
    return f"<h1>User #{user_id}</h1>"

**Comment by h-janes** [comment]
Hi,
This error is from Flask, not Flask Sitemapper.

You should have angular brackets `< ... >` around the URL variable in the Flask route, like this:
```python
@sitemapper.include(url_variables={"user_id": [1, 2, 3]})
@blog_bp.route("/user/<int:user_id>") # here
def r_user(user_id):
  return f"User #{user_id}"
```

I think this is the reason you are getting this error.

Let me know if this solves your issue! Thanks.

**Comment by deepdatadive** [comment]
Oops, sorry I don'tknow why the angular brackets didn't show up on my posted code. They are indeed there. I was just using the exact code posted in the documentation when I get the error. Tagging a route with the sitemapper.include() works just fine. It is just adding the dynamic URL doesn't.

I should mention that the route itself works fine. It is only the rendered XML page that doesn't function and returns that error when I visit it. I am still able to go to the route with 1, 2, or 3 and it functions. Also, any other @sitemapper.include() works when rendering the sitemap... just not when any dynamic routes are included. Could it have to do with a dynamic route inside of a blueprint?

```
@sitemapper.include(url_variables={"user_id": [1, 2, 3]})
@blog_bp.route("/user/<int:user_id>")
def r_user(user_id):
    return f"<h1>User #{user_id}</h1>" 
```

**Comment by h-janes** [comment]
Thanks for the reply, I have found the issue.

I made a mistake in the code meaning that dynamic routes weren't working properly with deferred initialisation e.g. `sitemapper.init_app(app)` if they were defined before this. 

I have fixed this mistake in the last commit in `sitemapper.py` and have included this fix in [the latest release 1.6.1](https://pypi.org/project/flask-sitemapper/)

It is now working for me, let me know if this fixes it for you!

**Comment by deepdatadive** [comment]
Thank you for fixing that. It currently works correctly on localhost. It builds the dynamic URLs for the XML. However (and this may just be a problem with my deployment), It gives the same error on my deployment server as it gave on localhost.  It still builds the static URLs correctly on the deployment server. I don't know if this issue is related or if it just something with my deployment being funky. You would probably know better.

**Comment by h-janes** [comment]
I'm not sure what could be causing that. Are you sure your server has the latest version (1.6.1)?
