### ISSUE TITLE
Use multiples values for lastmod when use url generator with variable

### ISSUE THREAD

**Issue by alberic89** [h-janes/flask-sitemapper#9]
It would be nice to be able to specify a different value for lastmod for each url_variables value when using an url generator.
I made a little hack, on [my fork](https://github.com/alberic89/flask-sitemapper), but it's anything but clean.

**Comment by h-janes** [comment]
Hi, good idea! I like the way you have done it. I will work to merge this and update the docs, thank you!

**Comment by h-janes** [comment]
I just thought that if lastmod values can be provided as a list then changefreq and priority should also probably have this option, so I'm thinking of doing something like this - will try to think of a cleaner way though, lmk what you think

`sitemapper.py @ line 104`
```python
        # if url variables are provided (for dynamic routes)
        if url_variables:
            # create a URL object for each set of url variables and append it to self.urls
            for i, v in enumerate(
                [dict(zip(url_variables, j)) for j in zip(*url_variables.values())]
            ):
                # use sitemap args from the list if a list is provided
                l = lastmod[i] if isinstance(lastmod, list) else lastmod
                c = changefreq[i] if isinstance(changefreq, list) else changefreq
                p = priority[i] if isinstance(priority, list) else priority
                # create URL object
                url = URL(endpoint, self.scheme, l, c, p, v)
                self.urls.append(url)
```
